config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  resources :users
  resources :users
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  get '/signin',  to: 'sessions#new'
  get '/signout', to: 'sessions#destroy'
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'sessions/new'

  get 'welcome/index'

  resources :appointments
  resources :pets
  resources :doctors

  root 'welcome#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Clinica ACP</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="hero">
<nav class="navbar navbar-default" role="navigation">
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <% if session[:user_id] %>
      <li class="active"><a><%= link_to "Inicio", root_path %> &nbsp;&nbsp;&nbsp;&nbsp;</a></li>
      <li class="active"><a><%= link_to "Doctor", doctors_path %> &nbsp;&nbsp;&nbsp;&nbsp;</a></li>
      <li class="active"><a><%= link_to "Mascota", pets_path %> &nbsp;&nbsp;&nbsp;&nbsp;</a></li>
      <li class="active"><a><%= link_to "Cita", appointments_path %> &nbsp;&nbsp;&nbsp;&nbsp;</a></li>
      <li class="active"><a><%= link_to 'Users', users_path %> &nbsp;&nbsp;&nbsp;&nbsp;</a></li>
  <%= button_to 'Cerrar Session', logout_path, method: :delete   %>
        <% end %>
        
      </li>
    </ul>

  </div><!-- /.navbar-collapse -->
</nav>
<div class="container">
    <%= yield %>  
</div>
  </div>
</body>
</html>